version: '3'
services:
  api:
    build: ./api/
    # image: resola-api:latest
    container_name: api
    ports:
      - 8081:8081
    env_file:
      - api.env
    depends_on:
      - postgres
    volumes:
      - ./api/app:/app/
      - ./images:/images/
      - ./logs/:/logs/
    
  postgres:
    image: postgres:13.1
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api
    volumes:
      - ./init_sql:/mnt/init_sql
    ports:
      - 5432:5432
  