version: '3'
services:
  api:
    build: ./api/
    # image: resola-api:latest
    container_name: api
    ports:
      - 8081:8081
    env_file:
      - api.env
    volumes:
      - ./api/app:/app/
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8081 --reload"
    