version: '3'
services:
  api:
    build: ./api/
    # image: resola-api:latest
    container_name: api
    ports:
      - 8081:8081
    env_file:
      - api.env
    depends_on:
      - postgres
    volumes:
      - ./api/app:/app/
      - ./images:/images/
      - ./logs/api:/logs/

  redis:
    image: redis:alpine3.18
    container_name: redis
    ports:
      - 6379:6379
    command:
      redis-server --requirepass 123456

  rabbitmq:
    image: rabbitmq:3.9.29-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
       - rabbitmq.env

  postgres:
    image: postgres:13.1
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api
    volumes:
      - ./init_sql:/mnt/init_sql
    ports:
      - 5432:5432

  worker:
    build: ./worker/
    container_name: worker
    env_file: 
      - worker.env
    volumes:
      - ./worker/app:/app/
      - ./logs/celery:/logs/