version: '3'
services:  
  postgres:
    image: postgres:13.1
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api
    volumes:
      - ./init_sql:/mnt/init_sql
    ports:
      - 5432:5432